# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('color', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('hair_growth', models.FloatField(blank=True, null=True)),
                ('milk_by_lactation', models.FloatField(blank=True, null=True)),
                ('duration_of_lactation', models.IntegerField(blank=True, null=True)),
                ('exploitation', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'breed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=5)),
                ('num', models.IntegerField()),
                ('ext', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('localisation', models.CharField(max_length=255)),
                ('identification', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Breed')),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Image')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'goat',
            },
        ),
    ]
